### ISSUE TITLE
GDM screen did not change

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/snapcraft-desktop-helpers#107]
Hi there!
I purged the ppa session and installed the snap. 
The snap did not install the GDM shell theme (for me). 
Did anyone else experience this? I am asking this because my host installation is doing strange things at the moment :) (upgrade from 17.04->17.10->18.04 was a bit too much)

**Comment by didrocks** [comment]
Hey @Feichtmeier, this is the wrong github project to post against, but I'm answering here ;) I guess you wanted to post against https://github.com/ubuntu/communitheme-snap-helpers.

This is actually on purpose. It's not because one user on the system changes its theme that all users should change (contrary to the ppa, which was really something deliberate) ;)
However, I provided a way to change that, basically, installing the css for GDM is:
```
  update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css \
    gdm3.css /snap/communitheme/current/share/gnome-shell/theme/communitheme/gnome-shell.css 15
```

Removing it is:
```
update-alternatives --remove gdm3.css /snap/communitheme/current/share/gnome-shell/theme/communitheme/gnome-shell.css
```

Writing it makes me think that this should be actually `communitheme.set-default-login` and `communitheme.remove-default-login`. I'm opened to better name and a bug report against the above project to get to it! :)

**Comment by didrocks** [comment]
(closing on that project)
