### ISSUE TITLE
GST_PLUGIN_PATH missing from desktop-exports

### ISSUE THREAD

**Issue by michihenning** [ubuntu/snapcraft-desktop-helpers#43]
We need to snap something that uses ubuntu-app-platform, and we launch our binaries with desktop-launch. The code requires additional gstreamer plugins that are not present in ubuntu-app-platform. After installing the missing codecs into our snap, gstreamer still fails because it can't find the plugin-scanner.

I can work around the issue by doing this in the code:

`setenv("GST_PLUGIN_SCANNER", "/snap/ubuntu-app-platform/current/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner", 1);`

I believe desktop-exports should be setting this.

**Comment by didrocks** [comment]
I'm ok with adding this path for now. Note that GST_PLUGIN_PATH is already added contrary to the bug title, I added GST_PLUGIN_SCANNER one. However, the first should have been suffcieitn.
Can you ensure you keep the desktop team in loop for this? For me, the plugin should be alongside others (which are already exported in desktop-launch) in `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/` instead of `/usr/lib/x86_64-linux-gnu/gstreamer1.0`. That will then be detected automatically. I guess it's a simple packaging fix.

Pushed the fix for adding this env variable. Ping the sdk team to update the platform snap to include it.

**Comment by michihenning** [comment]
Thanks Didier! Sorry for the wrong title, I meant GST_PLUGIN_SCANNER, of course. I've updated the title to match reality :)

I tried with just GST_PLUGIN_PATH set, and that didn't work. I got the plugins loaded only after I also set GST_PLUGIN_SCANNER.
