### ISSUE TITLE
Fonts are missing from Electron applications when the desktop and desktop-legacy interfaces are defined

### ISSUE THREAD

**Issue by flexiondotorg** [Ubuntu/snapcraft-desktop-helpers#89]
We recently added `desktop` and `desktop-legacy` interfaces to some Electron snaps maintained by the Snapcrafter community. 

  * https://github.com/snapcrafters/wordpress-desktop/commit/7bed60590a23a5bb458d55348ba16f26d6791d82

We noticed that fonts we missing from the Electron applications after doing this. We first tried just adding back the `x11` interface, but this didn't resolve the issue. We then removed and the `desktop` and `desktop-legacy` interfaces and fonts were restored.

It is worth noting that, currently, all Electron applications are linked against GTK+2 and use the `desktop-gtk2` launcher.

I am seeing AppArmor denials, such as these, when launching strictly confined Electron applications:

```
Dec 18 16:25:26 skull kernel: [ 7884.078907] audit: type=1400 audit(1513614326.3
83:877): apparmor="DENIED" operation="open" profile="snap.cumulonimbus.cumulonimbus" name="/home/martin/.local/share/fonts/" pid=28254 comm="cumulonimbus" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
Dec 18 16:25:26 skull kernel: [ 7884.078909] audit: type=1400 audit(1513614326.383:878): apparmor="DENIED" operation="open" profile="snap.cumulonimbus.cumulonimbus" name="/home/martin/.local/share/fonts/" pid=28254 comm="cumulonimbus" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
Dec 18 16:25:26 skull kernel: [ 7884.078910] audit: type=1400 audit(1513614326.383:879): apparmor="DENIED" operation="open" profile="snap.cumulonimbus.cumulonimbus" name="/home/martin/.local/share/fonts/" pid=28254 comm="cumulonimbus" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

We discussed this issue with @kenvandine and raised this bug as a result.

**Comment by jhenstridge** [comment]
I downloaded the wordpress-desktop snapcraft project and added back the desktop interface, and built it with "snapcraft cleanbuild".  The resulting snap seemed to display fonts as expected.

As an added check, I decided to inspect what fonts were visible in the confined environment:

1. run "snap run --shell wordpress-desktop"
2. run the "export" commands from $SNAP/command-wordpress-desktop.wrapper in that shell.
3. run "desktop-launch fc-list | less"

This returned both fonts bundled with the snap (DejaVu, Ubuntu), and fonts from the host system.  The host system font files were readable for me.

Interestingly enough, I was responding to a user who was running into font related issues with their snap on Fedora and Solus:

https://forum.snapcraft.io/t/could-not-find-any-font-error-on-solus-fedora/3251

He wasn't using the desktop interface, so I'm not sure if that is the root cause of the problem.  If you've got a system suffering from the problem, it would be useful to get the following info:

1. what is the host system? (distro, flavour, architecture)

2. do you get any errors when running fc-list as described above?  Does it produce the expected list of fonts?

3. What is in the $SNAP_USER_DATA/.config/fontconfig/fonts.conf file generated by desktop-launch?

I think the AppArmor denials are also a red herring: the error is due to the `<abstractions/fonts>` AppArmor policy fragment missing this directory, but its omission shouldn't cause a failure.  It will simply fail to read fonts in that directory.

**Comment by galgalesh** [comment]
In the Mattermost snap, this was caused by the binary having the `stackexec` flag set. More info: https://forum.snapcraft.io/t/fonts-fail-to-load-when-desktop-plug-added/3414/3

**Comment by jhenstridge** [comment]
And the most recent commit when I was testing out the wordpress-desktop package cleared the executable stack flag:

https://github.com/snapcrafters/wordpress-desktop/commit/024661cff94c84c3a1ccd574ef51ef8405161366

So the problem can basically be broken down as follows:

1. By default, many Electron apps seem to be built with the executable stack flag set.
2. fontconfig and/or freetype attempt to create PROT_READ memory mappings of fonts and caches.  
3. When Linux loads a program with the executable stack flag set, it enables the "read implies exec" personality: https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/elf.h#L282-L287
3. The default AppArmor template is fairly selective in what file paths may be mapped with PROT_EXEC: mainly paths that represent shared libraries and a few others.  
4. The memory mapping fails because the implicit executable permission is denied for the location of the font.

There's nothing in this chain of events that we can really mitigate in snapcraft-desktop-helpers.  We can't do anything about the executable flags at runtime (the executable is in a read only filesystem), and there is no snapcraft hook that would let us alter files installed by subsequent parts.  Further more, it's not really something we should be doing in the first place: with modern toolchains, if an executable has this flag set, it probably needs it.

The fact that these Electron apps function correctly after manually clearing it sounds like a bug in the Electron build process.

**Comment by galgalesh** [comment]
We can't fix it in desktop-helpers, but we can check for the stackexec bit and throw a warning in the `desktop-launch` script, no? That would at least help a lot during debugging..

**Comment by flexiondotorg** [comment]
I have rebuilt all the affected Electron applications, adding the `desktop` interface and clearing the execstack if it is set.

All have working fonts.

@jhenstridge Thank you for investing. We have requested that `snapcraft` clear the execstack on binaries and print warnings if it does so.
